Added Extra helper functions
Whitebrim/AnimatedSprite pull request #16
Opened 2024-04-06 22:11 UTC by dganzella

Functions that were missing from the Animation system, it makes it more complete now

2024-04-06 22:34 UTC, Whitebrim commented
Who is debugchicken?

2024-04-07 00:08 UTC, dganzella commented
> Who is debugchicken?

its me!

unless thats a rhetorical question

2024-04-11 00:08 UTC, Whitebrim commented
I'll take a closer look this weekend

2024-04-30 00:15 UTC, Whitebrim commented
`.states[]` is a public property, you can access it from outside.
https://github.com/Whitebrim/AnimatedSprite/wiki/Examples#example_3b

2024-04-30 02:28 UTC, Whitebrim requested changes
Some functions are redundant, you can directly call this properties.

2024-04-30 02:28 UTC, Whitebrim commented on AnimatedSprite.lua
> +
```suggestion
end

```

2024-04-30 02:28 UTC, Whitebrim commented on AnimatedSprite.lua
> +
Use `self.states.name` in your class. [Example](https://github.com/Whitebrim/AnimatedSprite/wiki/Examples#example_3b)

```suggestion
```

2024-04-30 02:28 UTC, Whitebrim commented on AnimatedSprite.lua
> +---@return table
Comments use EmmyLua style, so three `-` is required
```suggestion
---Get the current state
---@return table state Reference to the current state
```

2024-04-30 02:28 UTC, Whitebrim commented on AnimatedSprite.lua
> +end
Just use `self.currentState` in your class. [Example](https://github.com/Whitebrim/AnimatedSprite/wiki/Examples#example_3a)

```suggestion
```

2024-04-30 02:28 UTC, Whitebrim commented on AnimatedSprite.lua
> +---Get the current index in the array animation (aka, 1,2,3,n, where n = number of frames). good for starting another animation of same size from the same position of this animation
Added more clarity
```suggestion
---Get the current frame's local index in the state (i.e. 1, 2, 3, n. where n = number of frames in this state)
```

2024-04-30 02:28 UTC, Whitebrim commented on AnimatedSprite.lua
> +function AnimatedSprite:getCurrentFrameIndexInAnimationArray()
```suggestion
function AnimatedSprite:getCurrentFrameLocalIndex()
```

2024-04-30 02:30 UTC, dganzella commented
you are right, im Sorry Im new to lua I did not realize this

2024-04-30 02:42 UTC, Whitebrim commented
@dganzella You had two usefull functions, please accept all my suggestions and I'll merge it.

2024-04-30 02:57 UTC, Whitebrim approved these changes

2024-04-30 02:57 UTC, dganzella commented
ok @Whitebrim I think I accepted them all (I was at the app and the app does not let me add your changed, so I was a bit confused -- only the website lets me accept changes)

2024-04-30 02:58 UTC, merged